@echo off
echo Starting Backend (node server.js)...
start "Backend Server" cmd /k "cd backend && node server.js"

echo Starting Frontend (npm run dev)...
start "Frontend Server" cmd /k "cd frontend && npm run dev"

echo Both servers are starting...
